/*
 * Keypress-driven bongo cat widget (per-half paws).
 *
 * Art generated by gen_bongo_art.py (44x18, transparent background).
 *
 * SPDX-License-Identifier: MIT
 */

#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>

#include <zmk/display.h>
#include <zmk/event_manager.h>
#include <zmk/events/position_state_changed.h>
#include <lvgl.h>

#include "bongo_cat.h"

LOG_MODULE_DECLARE(zmk, CONFIG_ZMK_LOG_LEVEL);

LV_IMG_DECLARE(bongo_none);
LV_IMG_DECLARE(bongo_left);
LV_IMG_DECLARE(bongo_right);
LV_IMG_DECLARE(bongo_both);

static sys_slist_t widgets = SYS_SLIST_STATIC_INIT(&widgets);

struct bongo_cat_state {
    bool left_down;
    bool right_down;
};

// Keys currently held on each half, tracked in the event accessor (runs per event) so the UI callback just renders the resulting paw positions.
static int left_held = 0;
static int right_held = 0;

static struct bongo_cat_state bongo_cat_get_state(const zmk_event_t *eh) {
    const struct zmk_position_state_changed *ev = as_zmk_position_state_changed(eh);
    if (ev != NULL) {
        bool is_left = (ev->source == ZMK_POSITION_STATE_CHANGE_SOURCE_LOCAL);
        int *held = is_left ? &left_held : &right_held;
        if (ev->state) {
            (*held)++;
        } else if (*held > 0) {
            (*held)--;
        }
    }
    return (struct bongo_cat_state){.left_down = left_held > 0, .right_down = right_held > 0};
}

static void bongo_cat_set_img(lv_obj_t *img, struct bongo_cat_state state) {
    const lv_img_dsc_t *frame;
    if (state.left_down && state.right_down) {
        frame = &bongo_both;
    } else if (state.left_down) {
        frame = &bongo_left;
    } else if (state.right_down) {
        frame = &bongo_right;
    } else {
        frame = &bongo_none;
    }
    lv_img_set_src(img, frame);
}

static void bongo_cat_update_cb(struct bongo_cat_state state) {
    struct zmk_widget_bongo_cat *widget;
    SYS_SLIST_FOR_EACH_CONTAINER(&widgets, widget, node) { bongo_cat_set_img(widget->obj, state); }
}

ZMK_DISPLAY_WIDGET_LISTENER(widget_bongo_cat, struct bongo_cat_state, bongo_cat_update_cb,
                            bongo_cat_get_state)
ZMK_SUBSCRIPTION(widget_bongo_cat, zmk_position_state_changed);

int zmk_widget_bongo_cat_init(struct zmk_widget_bongo_cat *widget, lv_obj_t *parent) {
    widget->obj = lv_img_create(parent);
    lv_img_set_src(widget->obj, &bongo_none);

    sys_slist_append(&widgets, &widget->node);

    widget_bongo_cat_init();
    return 0;
}

lv_obj_t *zmk_widget_bongo_cat_obj(struct zmk_widget_bongo_cat *widget) { return widget->obj; }
